snippets:
  - name: "null"
    keyword: "null"
    snippet: ">/dev/null 2>&1"
    # auto expand: condition
    # if not defined, it is only valid at the beginning of a line
    context:
      # buffer: ''
      lbuffer: '.+\s'
      # rbuffer: ''
    global: true
